-- Part A --

--Create a nested table type to store multiple gift items (e.g., 'Teddy Bear','Chocolate Box').

CREATE OR REPLACE TYPE GiftItemsType IS TABLE OF VARCHAR2(50);

--Create a table GIFT_CATALOG

CREATE TABLE Gift_Catalog (
    gift_id NUMBER PRIMARY KEY,
    min_purchase NUMBER,
    gifts GiftItemsType
) NESTED TABLE gifts STORE AS g_tab;

-- Insert at least three gift packages, each containing multiple gift items.

INSERT INTO Gift_Catalog VALUES (1, 100, GiftItemsType('Stickers', 'Pen Set'));
INSERT INTO Gift_Catalog VALUES (2, 1000, GiftItemsType('Teddy Bear', 'Mug', 'Perfume'));
INSERT INTO Gift_Catalog VALUES (3, 10000, GiftItemsType('Backpack', 'Wireless Earbuds', 'Fitness Tracker'));

-- Part B --

--Create a table CUSTOMER_REWARDS:

CREATE TABLE Customer_Rewards (
    reward_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_email VARCHAR2(255),
    gift_id NUMBER,
    reward_date DATE DEFAULT SYSDATE,
    FOREIGN KEY (gift_id) REFERENCES Gift_Catalog(gift_id)
);


-- Part C --

--Create a PL/SQL package named CUSTOMER_MANAGER that assigns gift
-- packages to customers based on the total value of their completed orders.

CREATE OR REPLACE PACKAGE Customer_Manager AS
    -- Public
    FUNCTION Get_Total_Purchase(p_customer_id NUMBER) RETURN NUMBER;
    PROCEDURE Assign_Gifts_To_All;
END CUSTOMER_MANAGER;
/

CREATE OR REPLACE PACKAGE BODY Customer_Manager AS
    -- Private
    FUNCTION Choose_Gift_Package(p_total_purchase NUMBER) RETURN NUMBER IS
        v_gift_id NUMBER;
    BEGIN
        SELECT gift_id INTO v_gift_id
        FROM Gift_Catalog
        WHERE min_purchase = (
            SELECT MAX(min_purchase)
            FROM Gift_Catalog
            WHERE min_purchase <= p_total_purchase
        );

        RETURN v_gift_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END Choose_Gift_Package;

    -- Implementation of public functions
    FUNCTION Get_Total_Purchase(p_customer_id NUMBER) RETURN NUMBER IS
        v_total_purchase NUMBER;
    BEGIN
        SELECT NVL(SUM(oi.unit_price * oi.quantity), 0) INTO v_total_purchase -- if no orders, then 0
        FROM Orders o
        JOIN Order_Items oi ON o.order_id = oi.order_id
        WHERE o.customer_id = p_customer_id;

        RETURN v_total_purchase;
    END Get_Total_Purchase;

    PROCEDURE Assign_Gifts_To_All IS
        v_total_purchase NUMBER;
        v_gift_id NUMBER;
    BEGIN
        FOR cust_rec IN 
            (SELECT customer_id, email_address AS email
             FROM Customers
            ) LOOP
            v_total_purchase := Get_Total_Purchase(cust_rec.customer_id);
            v_gift_id := Choose_Gift_Package(v_total_purchase);

            IF v_gift_id IS NOT NULL THEN
                INSERT INTO Customer_Rewards (customer_email, gift_id)
                VALUES (cust_rec.email, v_gift_id);
            END IF;
        END LOOP;
    END Assign_Gifts_To_All;

END CUSTOMER_MANAGER;


-- Part D --

--Implement a procedure that joins the CUSTOMER_REWARDS and GIFT_CATALOG 
--tables and displays the results for the first five customers. Capture a 
--screenshot of the output.

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE Display_Customer_Rewards IS
    --v_gift_id NUMBER;
    --v_min_purchase NUMBER;
    --v_gifts GiftItemsType;
    v_count NUMBER := 0;
BEGIN
    FOR rec IN (
        SELECT cr.customer_email, gc.gift_id, gc.min_purchase, gc.gifts
        FROM Customer_Rewards cr 
        JOIN Gift_Catalog gc ON cr.gift_id = gc.gift_id
    )LOOP
        v_count := v_count + 1;

        --Output
        DBMS_OUTPUT.PUT_LINE('Customer Email: ' || rec.customer_email);
        DBMS_OUTPUT.PUT_LINE('Gift ID: ' || rec.gift_id);
        DBMS_OUTPUT.PUT_LINE('Minimum Purchase: ' || rec.min_purchase);
        DBMS_OUTPUT.PUT_LINE('Gift ID: ' || rec.gift_id);

        EXIT WHEN v_count >= 5;

        DBMS_OUTPUT.PUT_LINE('-------------------------');
    END LOOP;
END Display_Customer_Rewards;
/

BEGIN
    Display_Customer_Rewards;
END;

--SELECT * FROM Customer_Rewards;